Repository Programmers-SpotLight/SpotLight, pull requests merged in 2024-08, with the labels that each got.

#15 FEAT : 공통 컴포넌트 header 구현
  src/app/layout.tsx
  src/components/common/Header.tsx
  tailwind.config.ts
Labels: enhancement

#17 FEAT : 셀렉션 페이지 생성
  src/app/selection/[selectionId]/page.tsx
Labels: enhancement

#19 FEAT : drawer 구현
  src/app/selection/[selectionId]/page.tsx
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/SpotSection.tsx
Labels: enhancement

#25 fix : drawer 찌그러짐 해결
  src/app/selection/[selectionId]/page.tsx
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/SpotSection.tsx
Labels: enhancement

#23 FEAT : tabs 구현
  src/components/common/Tabs.tsx
  src/components/selection-detail/SpotSection.tsx
Labels: enhancement

#26 FIX : translate-x 수정
  src/components/selection-detail/SpotSection.tsx
Labels: bug

#30 Feat: DB 연결 기능 추가
  .gitignore
  jest.config.ts
  package-lock.json
  package.json
  src/libs/.gitkeep
  src/libs/__test__/db.test.ts
  src/libs/db.ts
  tsconfig.test.json
Labels: enhancement

#36 Feature/#28 selection detail UI
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/components/selection-detail/selection-section-contents/SelectionInfo.tsx
  src/components/selection-detail/selection-section-contents/SelectionReview.tsx
  src/components/selection-detail/selection-section-contents/SpotList.tsx
  src/models/selection.ts
Labels: enhancement

#38 Feat/#27 selection detail spot UI
  public/icons/spot/관광지.svg
  public/icons/spot/기타.svg
  public/icons/spot/맛집.svg
  public/icons/spot/쇼핑.svg
  public/icons/spot/카페.svg
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/spot/SpotImages.tsx
  src/components/selection-detail/spot/SpotSection.tsx
Labels: enhancement

#41 REFAC : 셀렉션 디테일 페이지
  package-lock.json
  package.json
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotImages.tsx
  src/components/selection-detail/spot-selection-contents/SpotInfo.tsx
  src/components/selection-detail/spot-selection-contents/SpotReview.tsx
  tailwind.config.ts
Labels: refactor

#43 Feat : 모달 데이터 입력 인자 추가, 조건부 오버레이 클릭 이벤트 추가
  src/components/common/modal/ModalController.tsx
  src/components/common/modal/modal-contents/ModalTemp.tsx
  src/stores/modalStore.ts
Labels: enhancement

#49 FEAT : google map 생성
  package-lock.json
  package.json
  public/icons/map-pin/맵핀-관광지.svg
  public/icons/map-pin/맵핀-기타.svg
  public/icons/map-pin/맵핀-맛집.svg
  public/icons/map-pin/맵핀-쇼핑.svg
  public/icons/map-pin/맵핀-카페.svg
  public/icons/map-pin/맵핀-현위치.svg
  public/icons/spot/기타.svg
  public/icons/spot/현위치.svg
  src/app/selection/[selectionId]/page.tsx
  src/components/google-map/GoogleMap.tsx
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
Labels: enhancement

#52 Feat : http client 모듈, request Handler 추가
  package-lock.json
  package.json
  src/http/http.ts
Labels: enhancement

#55 Chore : Knex 환경설정 추가
  next.config.mjs
Labels: enhancement

#56 Feat/#50 셀렉션 상세 페이지 props 정리
  src/app/selection/[selectionId]/page.tsx
  src/components/google-map/GoogleMap.tsx
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/components/selection-detail/selection-section-contents/SelectionInfo.tsx
  src/components/selection-detail/selection-section-contents/SpotList.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotInfo.tsx
  src/models/selection.ts
  src/models/spot.ts
Labels: enhancement

#58 FEAT : 이미지 상세보기
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalController.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotImages.tsx
  src/models/modal.ts
Labels: enhancement

#60 Feature/#2 (셀렉션 생성) 제목 입력
  package-lock.json
  package.json
  public/icons/add_7C7C7C.svg
  public/icons/arrow_drop_down_02588E.svg
  public/icons/arrow_drop_up_02588E.svg
  public/icons/arrow_forward_7C7C7C.svg
  public/icons/clear_7C7C7C.svg
  public/icons/location_on_7C7C7C.svg
  public/icons/move_7C7C7C.svg
  public/icons/photo_camera_7C7C7C.svg
  src/app/api/selections/categories/route.ts
  src/app/api/selections/locations/route.ts
  src/app/api/selections/route.ts
  src/app/api/selections/spots/geolocate/route.ts
  src/app/api/selections/spots/reverse-geolocate/route.ts
  src/app/api/selections/spots/search/route.ts
  src/app/selection/create/page.tsx
  src/components/common/input/OneLineInput.tsx
  src/components/common/modal/ModalController.tsx
  src/components/common/modal/modal-contents/ModalCreateSelectionSpot.tsx
  src/components/selection-create/DropdownMenu.tsx
  src/components/selection-create/PoiMarkers.tsx
  src/components/selection-create/SelectionCreateCategory.tsx
  src/components/selection-create/SelectionCreateDescription.tsx
  src/components/selection-create/SelectionCreateForm.tsx
  src/components/selection-create/SelectionCreateLocation.tsx
  src/components/selection-create/SelectionCreateTitle.tsx
  src/hooks/queries/.gitkeep
  src/hooks/queries/selectionCreate.query.ts
  src/hooks/useGeocoding.ts
  src/hooks/useOutsideClick.ts
  src/hooks/useReverseGeocoding.ts
  src/hooks/useSelectionCategories.ts
  src/hooks/useSelectionLocations.ts
  src/hooks/useSpotSearch.ts
  src/models/modal.ts
  src/models/selection.model.ts
  src/services/selection-services.ts
  src/stores/modalStore.ts
  src/stores/selectionCreateStore.ts
Labels: bug, enhancement

#62 Bug/#61 셀렉션 생성 관련 모달창 열기 문제
  src/app/selection/create/page.tsx
  src/components/common/modal/ModalController.tsx
  src/components/selection-create/SelectionCreateForm.tsx
  src/models/modal.ts
Labels: bug

#67 Feat/#53 selection search
  next.config.mjs
  src/app/ClientRoot.tsx
  src/app/api/selections/categories/route.ts
  src/app/api/selections/search/route.ts
  src/app/api/selections/search/searchQueryBuilder.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/common/Banner.tsx
  src/components/common/Hashtag.tsx
  src/components/common/card/ColCard.tsx
  src/components/main/BannerSection.tsx
  src/components/main/InterestingSection.tsx
  src/components/search/Pagination.tsx
  src/components/search/SearchBannerSection.tsx
  src/components/search/SearchDropdown.tsx
  src/components/search/SearchEmptyResults.tsx
  src/components/search/SearchEngineSection.tsx
  src/components/search/SearchLoading.tsx
  src/components/search/SearchResultSection.tsx
  src/components/selection-detail/SelectionSection.tsx
  src/constants/id.ts
  src/constants/queryString.ts
  src/hooks/queries/useFetchSearchResult.ts
  src/hooks/queries/useFetchSelectionCategories.ts
  src/hooks/queries/useFetchSelectionLocations.ts
  src/http/search.api.ts
  src/mocks/.gitkeep
  src/models/hashtag.model.ts
  src/models/modal.model.ts
  src/models/searchResult.model.ts
  src/pages/.gitkeep
  src/services/selection-service.ts
Labels: documentation

#70 Refactor/selection creation
  src/app/api/selections/route.ts
  src/components/selection-create/SelectionCreateForm.tsx
  src/constants/.gitkeep
  src/constants/selection.constants.ts
  src/models/selection.model.ts
  src/services/selection.services.ts
  src/utils/fileStorage.ts
Labels: bug, refactor

#71 Feat : 상세 페이지 api 구현
  src/app/QueryProvider.tsx
  src/app/api/selections/[selectionId]/route.ts
  src/app/selection/[selectionId]/page.tsx
  src/components/common/modal/ModalController.tsx
  src/components/google-map/GoogleMap.tsx
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/components/selection-detail/selection-section-contents/SpotList.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotImages.tsx
  src/components/selection-detail/spot-selection-contents/SpotInfo.tsx
  src/hooks/queries/selectionDetail.query.ts
  src/hooks/useSelection.ts
  src/models/selection.ts
  src/models/spot.ts
  src/services/selection-detail-service.ts
Labels: enhancement

#75 Feature/#74 셀렉션 스팟 생성 카테고리 추가
  src/app/api/selections/spots/categories/route.ts
  src/components/common/modal/modal-contents/ModalCreateSelectionSpot.tsx
  src/components/selection-create/SelectionCreateForm.tsx
  src/hooks/queries/selectionCreate.query.ts
  src/hooks/useSpotCategories.ts
  src/models/selection.model.ts
  src/services/selection.services.ts
  src/services/spot.services.ts
  src/stores/modalStore.ts
  src/stores/selectionCreateStore.ts
Labels: enhancement

#77 Fix 셀렉션 상세 페이지 버그 수정
  src/app/ClientRoot.tsx
  src/components/common/modal/ModalController.tsx
  src/components/google-map/GoogleMap.tsx
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotImages.tsx
  src/services/selection-detail-service.ts
Labels: bug

#79 FEAT : map Loading 구현
  src/app/globals.css
  src/app/selection/[selectionId]/page.tsx
  src/components/google-map/MapLoading.tsx
Labels: enhancement

#81 REFAC : file 이동 및 queryProvider 삭제
  src/app/QueryProvider.tsx
  src/app/selection/[selectionId]/page.tsx
  src/hooks/queries/useSelectionDetail.ts
  src/http/selectionDetail.api.ts
Labels: refactor

#84 Feat/#69 search autocompletion
  package-lock.json
  package.json
  src/app/api/selections/search/auto-completion/route.ts
  src/components/common/Banner.tsx
  src/components/common/input/TextInput.tsx
  src/components/common/modal/Modal.tsx
  src/components/search/SearchEngineSection.tsx
  src/components/search/SearchResultSection.tsx
  src/components/search/search-contents/AutoCompletion.tsx
  src/components/search/search-contents/SearchDropdown.tsx
  src/components/search/search-contents/SearchEmptyResults.tsx
  src/components/search/search-contents/SearchLoading.tsx
  src/constants/queryString.ts
  src/hooks/queries/useFetchSearchAutoCompletion.ts
  src/hooks/useDeboune.ts
  src/http/search.api.ts
Labels: enhancement

#86 Refactor/selection create
  src/app/ClientRoot.tsx
  src/app/selection/create/page.tsx
  src/components/common/modal/modal-contents/ModalCreateSelectionSpot.tsx
  src/components/selection-create/SelectionCreateCategory.tsx
  src/components/selection-create/SelectionCreateForm.tsx
  src/components/selection-create/SelectionCreateFormLoadingSpinner.tsx
  src/components/selection-create/SelectionCreateHashtags.tsx
  src/components/selection-create/SelectionCreateLocation.tsx
  src/components/selection-create/SelectionCreateSpot.tsx
  src/components/selection-create/SelectionCreateSubmit.tsx
  src/components/selection-create/SelectionCreateThumbnailImage.tsx
  src/hooks/queries/selectionCreate.query.ts
  src/hooks/useGeocoding.ts
  src/hooks/useReverseGeocoding.ts
  src/hooks/useSelectionCategories.ts
  src/hooks/useSelectionLocations.ts
  src/hooks/useSpotCategories.ts
  src/hooks/useSpotSearch.ts
  src/http/http.ts
  src/http/selectionCreate.api.ts
Labels: bug, refactor

#89 Feat : 지역 카테고리 데이터 및 필터 기능 연결
  src/app/api/selections/search/route.ts
  src/components/common/card/ColCard.tsx
  src/components/search/SearchResultSection.tsx
  src/models/searchResult.model.ts
  src/services/selection-search.services.ts
Labels: enhancement

#91 Feat : 상세 페이지 버그 수정 & 파일 명 수정
  src/app/api/selections/[selectionId]/route.ts
  src/components/google-map/GoogleMap.tsx
  src/components/selection-detail/selection-section-contents/SpotList.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/models/selection.model.ts
  src/models/selection.ts
  src/models/spot.model.ts
  src/services/selectionDetail.services.ts
Labels: bug

#95 Refactor/#93 refactor 셀렉션 추가 리펙토링
  src/app/api/selections/route.ts
  src/app/selection/create/page.tsx
  src/components/selection-create/SelectionCreateForm.tsx
  src/services/selection.services.ts
  src/services/spot.services.ts
  src/utils/errors.ts
Labels: enhancement, refactor

#114 FEAT : drawer 오픈 여부에 따라 맵 크기 조절
  src/app/selection/[selectionId]/page.tsx
  src/components/google-map/GoogleMap.tsx
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
Labels: enhancement

#115 Feat/#105 검색 자동완성 리팩토링 및 버그 수정
  src/app/api/selections/search/auto-completion/route.ts
  src/app/api/selections/search/route.ts
  src/components/search/SearchEngineSection.tsx
  src/components/search/search-contents/AutoCompletion.tsx
  src/services/selection-search.services.ts
  src/services/selectionSearch.services.ts
Labels: refactor

#116 Refactor/selection create
  src/components/common/Dropdown.tsx
  src/components/common/modal/ModalController.tsx
  src/components/common/modal/modal-contents/ModalCreateSelectionSpot.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpot.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotAddButton.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotCategory.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotHashtags.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotImages.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotImagesInput.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotInfo.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotPlaceName.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotSearch.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotSearchBar.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotSearchMap.tsx
  src/components/selection-create/SelectionCreateCategory.tsx
  src/components/selection-create/SelectionCreateDescription.tsx
  src/components/selection-create/SelectionCreateForm.tsx
  src/components/selection-create/SelectionCreateHashtags.tsx
  src/components/selection-create/SelectionCreateHashtagsList.tsx
  src/components/selection-create/SelectionCreateHashtagsListItem.tsx
  src/components/selection-create/SelectionCreateHashtagsSuggestionList.tsx
  src/components/selection-create/SelectionCreateHashtagsSuggestionListItem.tsx
  src/components/selection-create/SelectionCreateHashtagsSuggestionListSpinner.tsx
  src/components/selection-create/SelectionCreateLocation.tsx
  src/components/selection-create/SelectionCreateSpot.tsx
  src/components/selection-create/SelectionCreateSubmit.tsx
  src/components/selection-create/SelectionCreateThumbnailImage.tsx
  src/components/selection-create/SelectionCreateTitle.tsx
  src/hooks/useHashtagSuggestion.ts
  src/stores/selectionCreateStore.ts
Labels: refactor

#117 Fix: 셀렉션 리셋 기능 추가
  src/components/selection-create/SelectionCreateSubmit.tsx
Labels: bug

#119 Feat : 인기 셀렉션 API 구현 및 연결
  src/app/api/selections/popular/route.ts
  src/app/api/selections/search/auto-completion/route.ts
  src/app/api/selections/search/route.ts
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/card/RowCard.tsx
  src/components/main/PopularSection.tsx
  src/components/search/SearchEngineSection.tsx
  src/components/search/SearchResultSection.tsx
  src/constants/queryString.constants.ts
  src/http/http.ts
  src/http/selectionCategory.api.ts
  src/http/selectionMain.api.ts
  src/http/selectionSearch.api.ts
  src/services/selectionMain.services.ts
Labels: enhancement

#111 Feat: 셀렉션/스팟 리뷰 좋아요 추가, 삭제 api 구현
  src/app/api/selections/[selectionId]/reviews/[reviewId]/likes/route.ts
  src/app/api/selections/[selectionId]/spots/[spotId]/reviews/[reviewId]/likes/route.ts
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/review/ReviewItem.tsx
  src/components/selection-detail/review/ReviewList.tsx
  src/components/selection-detail/review/ReviewModal.tsx
  src/components/selection-detail/review/selection-review/SelectionReview.tsx
  src/components/selection-detail/review/spot-review/SpotReview.tsx
  src/hooks/queries/useReviewsLikes.ts
  src/http/review.api.ts
  src/models/review.ts
  src/services/review.services.ts
Labels: enhancement

#120 Feature/#118 셀렉션 추가 페이지 수정 기능 구현
  src/app/api/selections/route.ts
  src/app/api/selections/spots/geolocate/route.ts
  src/app/api/selections/spots/reverse-geolocate/route.ts
  src/app/api/selections/suggest-hashtags/route.ts
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpot.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotAddButton.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotHashtags.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotInfo.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotSearchBar.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotSearchMap.tsx
  src/components/selection-create/PoiMarkers.tsx
  src/components/selection-create/SelectionCreateCategory.tsx
  src/components/selection-create/SelectionCreateDescription.tsx
  src/components/selection-create/SelectionCreateForm.tsx
  src/components/selection-create/SelectionCreateHashtags.tsx
  src/components/selection-create/SelectionCreateHashtagsSuggestionList.tsx
  src/components/selection-create/SelectionCreateHashtagsSuggestionListItem.tsx
  src/components/selection-create/SelectionCreateSpot.tsx
  src/components/selection-create/SelectionCreateSpotItem.tsx
  src/components/selection-create/SelectionCreateSubmit.tsx
  src/components/selection-create/SelectionCreateTitle.tsx
  src/hooks/useHashtagSuggestion.ts
  src/hooks/useModalExtraData.ts
  src/hooks/useSpotSearch.ts
  src/http/selectionCreate.api.ts
  src/models/selection.model.ts
  src/services/selection.services.ts
  src/stores/modalStore.ts
  src/stores/selectionCreateStore.ts
Labels: enhancement, refactor

#122 Feature/#121 셀렉션 추가 스팟 정렬 드래그 드랍 기능
  package-lock.json
  package.json
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpot.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotAddButton.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotHashtags.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotHashtagsInput.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotPlaceName.tsx
  src/components/selection-create/SelectionCreateForm.tsx
  src/components/selection-create/SelectionCreateHashtagInput.tsx
  src/components/selection-create/SelectionCreateHashtags.tsx
  src/components/selection-create/SelectionCreateHashtagsList.tsx
  src/components/selection-create/SelectionCreateHashtagsSuggestionList.tsx
  src/components/selection-create/SelectionCreateHashtagsSuggestionListItem.tsx
  src/components/selection-create/SelectionCreateSpot.tsx
  src/components/selection-create/SelectionCreateSpotDragAndDrop.tsx
  src/components/selection-create/SelectionCreateSpotItem.tsx
  src/components/selection-create/SelectionCreateSubmit.tsx
  src/components/selection-create/StrictModeDroppable.tsx
  src/hooks/useModalExtraData.ts
  src/hooks/useOpenSelectionSpotAddModal.ts
  src/hooks/useOpenSelectionSpotEditModal.ts
  src/hooks/useSaveSelectionSpot.ts
  src/hooks/useSubmitSelectionCreateForm.tsx
  src/stores/selectionCreateStore.ts
Labels: enhancement, refactor

#123 FEAT : hashtag에 link 추가
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
Labels: enhancement

#124 Feat : 사용자 페이지 ui 구현
  src/app/ClientRoot.tsx
  src/app/api/selections/[selectionId]/route.ts
  src/app/user/[userId]/page.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/components/selection-detail/selection-section-contents/SpotList.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotImages.tsx
  src/components/user/UserInfo.tsx
  src/components/user/other-user/PrivateUser.tsx
  src/models/selection.model.ts
  src/models/spot.model.ts
  src/models/user.model.ts
  src/services/selectionDetail.services.ts
Labels: enhancement

#130 Feat : 셀렉션 관리 탭 UI 구현, 셀렉션 메뉴 리스트 UI 구현
  src/app/user/[userId]/layout.tsx
  src/components/common/card/ColCard.tsx
  src/components/user/my/UserInfoWidget.tsx
  src/components/user/my/UserNavigation.tsx
  src/components/user/my/UserSelectionList.tsx
  src/constants/queryString.constants.ts
  src/hooks/useClickOutside.ts
  src/models/user.model.ts
Labels: enhancement

#132 FEAT : 북마크 추가 삭제 api 구현 (낙관적 업데이트 적용)
  src/app/api/selections/[selectionId]/bookmarks/route.ts
  src/app/api/selections/[selectionId]/route.ts
  src/app/selection/[selectionId]/page.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/hooks/queries/useBookMarks.ts
  src/hooks/queries/useSelectionDetail.ts
  src/http/bookmarks.api.ts
  src/http/selectionDetail.api.ts
  src/services/selection.services.ts
  src/services/selectionDetail.services.ts
Labels: enhancement

#135 FEAT : 좋아요 아이콘 대신 북마크로 변경
  src/components/common/card/ColCard.tsx
  src/components/common/card/RowCard.tsx
Labels: enhancement

#137 FIX : 쿼리 무효화 대신 수동으로 데이터 업데이트
  src/hooks/queries/useBookMarks.ts
Labels: bug

#139 Refactor: 백엔드 리펙토링
  src/app/api/selections/categories/route.ts
  src/app/api/selections/locations/route.ts
  src/app/api/selections/route.ts
  src/app/api/selections/spots/reverse-geolocate/route.ts
  src/app/api/selections/spots/search/route.ts
  src/app/api/selections/suggest-hashtags/route.ts
  src/components/selection-create/SelectionCreateCategory.tsx
  src/components/selection-create/SelectionCreateDescription.tsx
  src/components/selection-create/SelectionCreateLocation.tsx
  src/components/selection-create/SelectionCreateSpot.tsx
  src/components/selection-create/SelectionCreateTitle.tsx
  src/hooks/useHashtagSuggestion.ts
  src/models/selection.model.ts
  src/services/selection.services.ts
  src/services/spot.services.ts
Labels: duplicate, refactor

#142 Feat/#102 user selection api
  src/app/api/users/[userId]/selections/route.ts
  src/app/user/[userId]/layout.tsx
  src/app/user/[userId]/page.tsx
  src/components/common/card/TempCard.tsx
  src/components/search/SearchResultSection.tsx
  src/components/user/my/UserSelectionList.tsx
  src/components/user/my/UserSelectionSection.tsx
  src/components/user/my/UserSelectionTempList.tsx
  src/constants/queryString.constants.ts
  src/constants/selection.constants.ts
  src/hooks/queries/useFetchUserSelectionList.ts
  src/hooks/useSelectionSort.tsx
  src/http/selectionSearch.api.ts
  src/models/searchResult.model.ts
  src/services/selectionSearch.services.ts
  src/services/selectionUser.services.ts
  src/utils/formatDate.ts
Labels: enhancement

#147 FEAT : 피드백 폼 ui 구현
  src/components/common/Footer.tsx
  src/components/common/input/PictureInput.tsx
  src/components/common/modal/ModalController.tsx
  src/components/common/modal/modal-contents/ModalFeedbackForm.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/models/modal.model.ts
Labels: enhancement

#150 Feat/#101 유저 정보 위젯 API 구현 및 연결
  src/app/api/users/[userId]/route.ts
  src/app/api/users/[userId]/selections/route.ts
  src/app/user/[userId]/layout.tsx
  src/app/user/[userId]/page.tsx
  src/components/common/card/ColCard.tsx
  src/components/common/modal/modal-contents/ModalEditTag.tsx
  src/components/user/UserInfo.tsx
  src/components/user/UserInfoWidget.tsx
  src/components/user/my/UserInfoWidget.tsx
  src/components/user/my/UserNavigation.tsx
  src/components/user/my/UserSelectionList.tsx
  src/components/user/my/UserSelectionSection.tsx
  src/components/user/my/UserSelectionTempList.tsx
  src/hooks/queries/useFetchUserInfo.ts
  src/hooks/queries/useFetchUserSelectionList.ts
  src/http/selectionSearch.api.ts
  src/http/user.api.ts
  src/models/hashtag.model.ts
  src/models/searchResult.model.ts
  src/models/user.model.ts
  src/services/user.services.ts
Labels: enhancement

#152 FIX : 스팟 이미지 없을 때 처리
  src/app/api/selections/[selectionId]/route.ts
  src/app/selection/[selectionId]/page.tsx
  src/components/google-map/GoogleMap.tsx
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/selection-section-contents/SpotList.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/hooks/queries/useSelectionDetail.ts
  src/models/selection.model.ts
  src/models/spot.model.ts
  src/services/selectionDetail.services.ts
Labels: bug

#155 Feat/#126#128 kakao signup and signin
  package-lock.json
  package.json
  src/app/ClientRoot.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/users/signin/route.ts
  src/app/api/users/signup/route.ts
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/common/Header.tsx
  src/components/common/modal/ModalController.tsx
  src/components/users/ModalUser.tsx
  src/components/users/SignIn.tsx
  src/components/users/SignUp.tsx
  src/services/users.services.ts
Labels: enhancement

#156 Feat/#151 my page user info api
  src/app/api/selections/search/route.ts
  src/app/api/users/[userId]/description/route.ts
  src/app/api/users/[userId]/hashtag/route.ts
  src/app/api/users/[userId]/selections/route.ts
  src/app/user/[userId]/layout.tsx
  src/app/user/[userId]/page.tsx
  src/components/common/card/ColCard.tsx
  src/components/common/card/TempCard.tsx
  src/components/common/modal/ModalController.tsx
  src/components/common/modal/modal-contents/ModalEditInfo.tsx
  src/components/common/modal/modal-contents/ModalEditTag.tsx
  src/components/common/modal/modal-contents/ModalTemp.tsx
  src/components/search/SearchEngineSection.tsx
  src/components/search/SearchResultSection.tsx
  src/components/search/search-contents/SearchLoading.tsx
  src/components/user/UserInfoWidget.tsx
  src/components/user/my/UserSelectionList.tsx
  src/components/user/my/UserSelectionSection.tsx
  src/components/user/my/UserSelectionTempList.tsx
  src/constants/selection.constants.ts
  src/hooks/queries/useFetchUserInfo.ts
  src/hooks/queries/useFetchUserSelectionList.ts
  src/hooks/queries/useUpdateUserDescription.ts
  src/hooks/queries/useUpdateUserHashtag.ts
  src/hooks/useSearchAutoComplete.ts
  src/http/user.api.ts
  src/models/searchResult.model.ts
  src/models/user.model.ts
  src/services/user.services.ts
Labels: enhancement

#161 FEAT : 유저 정보 추가
  src/app/api/selections/[selectionId]/route.ts
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/models/selection.model.ts
  src/models/user.model.ts
  src/services/selectionDetail.services.ts
Labels: enhancement

#160 FEAT : 다른 사용자 페이지
  src/app/api/users/[userId]/selections/route.ts
  src/app/user/[userId]/layout.tsx
  src/app/user/[userId]/page.tsx
  src/app/user/[userId]/review/page.tsx
  src/components/common/card/ColCard.tsx
  src/components/user/UserInfoWidget.tsx
  src/components/user/my/UserSelectionList.tsx
  src/components/user/my/UserSelectionSection.tsx
  src/constants/queryString.constants.ts
  src/context/UserPageContext.tsx
  src/hooks/queries/useFetchUserSelectionList.ts
  src/http/user.api.ts
  src/services/selectionUser.services.ts
Labels: enhancement

#174 Feature/메시지 큐 시스템 추가
  next.config.mjs
  package-lock.json
  package.json
  src/app/api/route.ts
  src/app/api/selections/route.ts
  src/app/api/selections/spots/geolocate/route.ts
  src/app/api/selections/spots/reverse-geolocate/route.ts
  src/app/api/selections/spots/search/route.ts
  src/app/api/selections/suggest-hashtags/route.ts
  src/instrumentation.ts
  src/libs/db.ts
  src/libs/queue.ts
  src/libs/redis.ts
  src/repositories/hashtag.repository.ts
  src/repositories/selection.repository.ts
  src/repositories/spot.repository.ts
  src/services/selection.services.ts
  src/services/selectionCreate.validation.ts
  src/services/spot.services.ts
  tsconfig.json
Labels: enhancement, refactor

#172 Feat: Footer 수정
  src/components/common/Footer.tsx
Labels: refactor

#178 FEAT : react-toastify 설치 및 alert 변경
  package-lock.json
  package.json
  src/app/ClientRoot.tsx
  src/app/layout.tsx
  src/components/common/input/PictureInput.tsx
  src/components/common/modal/modal-contents/ModalEditInfo.tsx
  src/components/common/modal/modal-contents/ModalEditTag.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotHashtagsInput.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotImagesInput.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotSearchBar.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotSearchMap.tsx
  src/components/selection-create/SelectionCreateHashtagInput.tsx
  src/components/selection-create/SelectionCreateHashtagsSuggestionListItem.tsx
  src/components/selection-create/SelectionCreateThumbnailImage.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/hooks/queries/useBookMarks.ts
  src/hooks/queries/useDeleteSelection.ts
  src/hooks/queries/useSendFeedback.ts
  src/hooks/queries/useUpdateUserSelectionPrivate.ts
  src/hooks/useHandleCardMenu.ts
  src/hooks/useHashtagSuggestion.ts
  src/hooks/useOpenSelectionSpotAddModal.ts
  src/hooks/useOpenSelectionSpotEditModal.ts
  src/hooks/useSaveSelectionSpot.ts
  src/hooks/useSubmitSelectionCreateForm.tsx
Labels: enhancement

#179 Refactor/#108 search api
  src/app/api/selections/search/route.ts
  src/app/api/users/[userId]/selections/route.ts
  src/components/common/Banner.tsx
  src/components/common/Header.tsx
  src/components/common/modal/modal-contents/ModalEditTag.tsx
  src/components/search/SearchEngineSection.tsx
  src/components/search/SearchResultSection.tsx
  src/components/search/search-contents/SearchErrorPage.tsx
  src/components/user/my/UserSelectionList.tsx
  src/hooks/queries/useFetchSearchResult.ts
  src/hooks/useSearchAutoComplete.ts
Labels: refactor

#180 Feat/#106 auto complete api
  src/app/api/selections/search/tag-recommend/route.ts
  src/components/common/Header.tsx
  src/components/common/modal/modal-contents/ModalEditInfo.tsx
  src/components/common/modal/modal-contents/ModalEditTag.tsx
  src/components/common/modal/modal-contents/ModalSelectionDelete.tsx
  src/components/search/SearchEngineSection.tsx
  src/components/search/search-contents/AutoCompletion.tsx
  src/components/search/search-contents/AutoCompletionList.tsx
  src/components/search/search-contents/AutoCompletionRecommendList.tsx
  src/hooks/mutations/useDeleteSelection.ts
  src/hooks/mutations/useUpdateUserDescription.ts
  src/hooks/mutations/useUpdateUserHashtag.ts
  src/hooks/mutations/useUpdateUserSelectionPrivate.ts
  src/hooks/queries/useFetchRecommendAutoCompletion.ts
  src/hooks/useHandleCardMenu.ts
  src/http/selectionSearch.api.ts
  src/services/selectionSearch.services.ts
Labels: enhancement

#181 FEAT : 에러 페이지 구현
  public/imgs/400.jpeg
  public/imgs/403.jpeg
  public/imgs/404.jpeg
  public/imgs/500.jpeg
  src/app/api/selections/[selectionId]/route.ts
  src/app/not-found.tsx
  src/app/selection/[selectionId]/page.tsx
  src/components/common/modal/Modal.tsx
  src/components/error/BadRequest.tsx
  src/components/error/Forbidden.tsx
  src/components/error/InternalServer.tsx
  src/components/error/NotFound.tsx
  src/hooks/queries/useSelectionDetail.ts
  src/hooks/useErrorComponents.tsx
  src/http/selectionDetail.api.ts
  src/utils/errors.ts
Labels: enhancement

#182 Feat/#154 Middleware 세팅, 세션 유저 id 추가
  public/imgs/google_web_light_sq_SI.svg
  public/imgs/kakao_login_medium_wide.png
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/users/signup/route.ts
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/common/Header.tsx
  src/components/common/button/Button.tsx
  src/components/common/modal/ModalController.tsx
  src/components/users/ModalSignIn.tsx
  src/components/users/ModalSignUp.tsx
  src/components/users/ModalUser.tsx
  src/components/users/SignIn.tsx
  src/components/users/SignUp.tsx
  src/hooks/useCheckSignUpParams.ts
  src/middleware.ts
  src/models/modal.model.ts
  src/models/next-auth.d.ts
  src/services/user.services.ts
  src/services/users.services.ts
  tsconfig.json
Labels: enhancement

#185 Feat: Middleware 세팅 및 Session 유저 id 정보 추가
  public/imgs/google_web_light_sq_SI.svg
  public/imgs/kakao_login_medium_wide.png
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/users/signup/route.ts
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/common/Header.tsx
  src/components/common/button/Button.tsx
  src/components/common/modal/ModalController.tsx
  src/components/users/ModalSignIn.tsx
  src/components/users/ModalSignUp.tsx
  src/components/users/ModalUser.tsx
  src/components/users/SignIn.tsx
  src/components/users/SignUp.tsx
  src/hooks/useCheckSignUpParams.ts
  src/middleware.ts
  src/models/modal.model.ts
  src/models/next-auth.d.ts
  src/services/user.services.ts
  src/services/users.services.ts
  tsconfig.json
Labels: enhancement

#188 Feat: Google 로그인 구현 외 기타 로그인 관련
  src/app/api/auth/[...nextauth]/route.ts
  src/components/common/Header.tsx
  src/components/common/button/Button.tsx
  src/components/users/ModalSignIn.tsx
  src/components/users/ModalSignUp.tsx
Labels: enhancement

#190 Fix: 스팟 수정 모달 열기 버그 수정
  public/icons/edit_7C7C7C.svg
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotImagesInput.tsx
  src/components/selection-create/SelectionCreateSpot.tsx
Labels: bug

#192 FEAT : 상세 페이지 userId 값 처리
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/selections/[selectionId]/route.ts
  src/app/selection/[selectionId]/page.tsx
  src/components/common/button/Button.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/hooks/queries/useBookMarks.ts
  src/services/selectionDetail.services.ts
Labels: enhancement

#193 Refactor/#186 검색 바 로딩창 및 핸들러 수정
  src/components/common/card/ColCard.tsx
  src/components/search/search-contents/AutoCompletion.tsx
  src/components/search/search-contents/AutoCompletionRecommendList.tsx
  src/components/search/search-contents/SearchLoading.tsx
Labels: refactor

#195 FEAT : 북마크 처리 로직 수정 & 사용자 페이지 isMyPage 처리
  src/app/api/selections/[selectionId]/bookmarks/route.ts
  src/app/api/selections/[selectionId]/route.ts
  src/app/user/[userId]/layout.tsx
  src/components/common/Header.tsx
  src/components/common/card/ColCard.tsx
  src/components/common/card/RowCard.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/hooks/queries/useBookMarks.ts
  src/hooks/useHandleCardMenu.ts
  src/services/selection.services.ts
  src/services/selectionDetail.services.ts
Labels: enhancement

#197 Feature/#191 셀렉션 추가 셀렉션 생성 시 사용자에게 셀렉션 부여
  src/app/api/selections/[selectionId]/details-for-edit/route.ts
  src/app/api/selections/[selectionId]/route.ts
  src/app/api/selections/route.ts
  src/app/api/temporary-selections/[selectionId]/route.ts
  src/app/api/temporary-selections/route.ts
  src/hooks/useSubmitSelectionCreateForm.tsx
  src/repositories/hashtag.repository.ts
  src/repositories/selection.repository.ts
  src/repositories/spot.repository.ts
  src/repositories/user.repository.ts
  src/services/selectionCreate.services.ts
  src/services/selectionCreate.validation.ts
  src/services/selectionEdit.services.ts
  src/services/spot.services.ts
  src/utils/authUtils.ts
Labels: bug, enhancement

#200 Feat: S3 연동
  src/app/api/upload/route.ts
  src/libs/s3.ts
Labels: enhancement

#202 Fix : 인기셀렉션 렌더 오류 수정
  src/services/selectionMain.services.ts
Labels: bug

#204 Feat/#194 my page/search page user
  src/app/api/selections/search/route.ts
  src/app/api/users/[userId]/selections/route.ts
  src/components/common/card/ColCard.tsx
  src/models/searchResult.model.ts
  src/services/selectionSearch.services.ts
  src/services/selectionUser.services.ts
Labels: enhancement

#206 Refactor/#170 review modal,like,code
  src/app/api/selections/[selectionId]/reviews/[reviewId]/likes/route.ts
  src/app/api/selections/[selectionId]/reviews/[reviewId]/route.ts
  src/app/api/selections/[selectionId]/reviews/reviews-info/route.ts
  src/app/api/selections/[selectionId]/reviews/route.ts
  src/app/api/selections/[selectionId]/spots/[spotId]/reviews/[reviewId]/likes/route.ts
  src/app/api/selections/spots/[spotId]/reviews/[reviewId]/route.ts
  src/app/api/selections/spots/[spotId]/reviews/reviews-info/route.ts
  src/app/api/selections/spots/[spotId]/reviews/route.ts
  src/app/api/users/reviews/selections/route.ts
  src/app/api/users/reviews/spots/route.ts
  src/app/selection/[selectionId]/page.tsx
  src/app/user/[userId]/review/page.tsx
  src/components/common/button/Button.tsx
  src/components/common/modal/modal-contents/review/ReviewModal.tsx
  src/components/selection-detail/SelectionSection.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/review/ReveiwError.tsx
  src/components/selection-detail/review/Review.tsx
  src/components/selection-detail/review/ReviewDeleteModal.tsx
  src/components/selection-detail/review/ReviewItem.tsx
  src/components/selection-detail/review/ReviewLikeButton.tsx
  src/components/selection-detail/review/ReviewList.tsx
  src/components/selection-detail/review/ReviewModal.tsx
  src/components/selection-detail/review/ReviewOrderButton.tsx
  src/components/user/my/review/MyReviewItem.tsx
  src/context/useReviewSortContext.tsx
  src/hooks/mutations/useMyReview.ts
  src/hooks/mutations/useReviewMutations.ts
  src/hooks/mutations/useReviewsLikes.ts
  src/hooks/queries/useReviewQuery.ts
  src/hooks/queries/useReviewsLikes.ts
  src/http/review.api.ts
  src/models/review.model.ts
  src/services/review.services.ts
  src/services/selectionReview.services.ts
  src/services/spotReview.services.ts
Labels: refactor

#207 Refactor/#205 mypage validator
  src/app/api/selections/[selectionId]/route.ts
  src/app/api/selections/search/route.ts
  src/app/api/users/[userId]/description/route.ts
  src/app/api/users/[userId]/hashtag/route.ts
  src/app/api/users/[userId]/selections/private/route.ts
  src/app/api/users/[userId]/selections/route.ts
  src/components/common/button/Button.tsx
  src/components/common/card/ColCard.tsx
  src/components/common/modal/modal-contents/ModalEditInfo.tsx
  src/components/common/modal/modal-contents/ModalSelectionDelete.tsx
  src/components/user/my/UserSelectionList.tsx
  src/components/user/my/UserSelectionSection.tsx
  src/hooks/mutations/useUpdateUserSelectionPrivate.ts
  src/hooks/useHandleCardMenu.ts
  src/http/user.api.ts
  src/services/selectionMain.services.ts
  src/services/selectionSearch.services.ts
  src/services/selectionUser.services.ts
  src/utils/authUtils.ts
Labels: refactor

#208 Feature/#191 셀렉션 추가 셀렉션 생성 시 사용자에게 셀렉션 부여
  src/app/api/route.ts
  src/components/common/DoubleDropdown.tsx
  src/components/common/SingleDropdown.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotCategory.tsx
  src/components/selection-create/SelectionCreateCategory.tsx
  src/components/selection-create/SelectionCreateLocation.tsx
  src/instrumentation.ts
  src/libs/queue.ts
  src/models/hashtag.model.ts
  src/models/selection.model.ts
  src/models/spot.model.ts
  src/repositories/hashtag.repository.ts
  src/repositories/selection.repository.ts
  src/repositories/spot.repository.ts
  src/repositories/user.repository.ts
  src/services/selectionCreate.services.ts
  src/services/selectionEdit.services.ts
  src/services/spot.services.ts
  src/stores/selectionCreateStore.ts
Labels: enhancement, refactor

#211 Fix: 서버 작동 에러 고침
  src/instrumentation.ts.bk
Labels: bug

#212 Feat: s3 connect
  package-lock.json
  package.json
  src/libs/s3.ts
Labels: refactor

#213 Fix: S3 ACL 설정 관련 수정
  src/libs/s3.ts
Labels: refactor

#217 FEAT : 이미지 src 설정 및 상세 페이지 버그 수정
  next.config.mjs
  src/app/selection/[selectionId]/page.tsx
  src/components/common/card/ColCard.tsx
  src/components/google-map/GoogleMap.tsx
  src/components/selection-detail/Drawer.tsx
  src/components/selection-detail/SpotSection.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/hooks/useSubmitSelectionCreateForm.tsx
Labels: bug, enhancement

#219 FEAT : public 폴더 정리 & daiseyui uninstall
  package-lock.json
  package.json
  public/icons/gitsvg.svg
  public/icons/notionsvg.svg
  public/imgs/banner/addBanner-Primary.png
  public/imgs/banner/mainBanner-idol.jpg
  public/imgs/banner/mainBanner-theater.jpg
  public/imgs/error/400.jpeg
  public/imgs/error/403.jpeg
  public/imgs/error/404.jpeg
  public/imgs/error/500.jpeg
  public/imgs/login/kakao_login_medium_wide.png
  public/next.svg
  public/vercel.svg
  src/components/common/Footer.tsx
  src/components/common/card/ColCard.tsx
  src/components/common/card/RowCard.tsx
  src/components/error/BadRequest.tsx
  src/components/error/Forbidden.tsx
  src/components/error/InternalServer.tsx
  src/components/error/NotFound.tsx
  src/components/main/BannerSection.tsx
  src/components/search/SearchBannerSection.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/components/users/ModalSignIn.tsx
  src/hooks/mutations/useBookMarks.ts
  tailwind.config.ts
Labels: refactor

#224 Feat/#222 마이페이지 프로필 이미지 수정 기능 추가
  src/app/api/users/[userId]/profile/route.ts
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/common/modal/modal-contents/ModalSelectionDelete.tsx
  src/components/user/UserInfoWidget.tsx
  src/components/user/UserProfileImage.tsx
  src/hooks/mutations/useUpdateUserProfileImage.ts
  src/http/http.ts
  src/http/user.api.ts
  src/services/user.services.ts
  src/utils/authUtils.ts
Labels: enhancement

#225 Refactor/#223 refactoring for build
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/selections/[selectionId]/reviews/[reviewId]/route.ts
  src/app/api/selections/[selectionId]/reviews/route.ts
  src/app/api/selections/[selectionId]/route.ts
  src/app/api/selections/categories/route.ts
  src/app/api/selections/locations/route.ts
  src/app/api/selections/popular/route.ts
  src/app/api/selections/search/route.ts
  src/app/api/selections/search/tag-recommend/route.ts
  src/app/api/selections/spots/[spotId]/reviews/[reviewId]/route.ts
  src/app/api/selections/spots/[spotId]/reviews/route.ts
  src/app/api/selections/spots/categories/route.ts
  src/app/api/users/[userId]/profile/route.ts
  src/app/api/users/[userId]/selections/route.ts
  src/app/api/users/reviews/selections/route.ts
  src/app/api/users/reviews/spots/route.ts
  src/app/selection/[selectionId]/edit/page.tsx
  src/app/selection/create/page.tsx
  src/app/temporary-selections/[selectionId]/edit/page.tsx
  src/components/common/input/PictureInput.tsx
  src/components/common/modal/modal-contents/ModalSelectionDelete.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotImagesInput.tsx
  src/components/selection-create/SelectionCreateThumbnailImage.tsx
  src/components/selection-detail/review/ReviewImageModal.tsx
  src/components/selection-detail/review/ReviewImages.tsx
  src/components/selection-detail/spot-selection-contents/SpotImages.tsx
  src/components/users/ModalSignIn.tsx
  src/libs/authOptions.ts
  src/services/user.services.ts
  src/utils/authUtils.ts
Labels: refactor

#227 Feat: 도커 이미지 빌드 파일 추가
  Dockerfile
  entrypoint.sh
  sys.sh
Labels: enhancement

#229 Refactor/#226 selection modify url
  src/app/api/users/[userId]/route.ts
  src/app/api/users/[userId]/selections/route.ts
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/common/card/ColCard.tsx
  src/components/common/card/TempCard.tsx
  src/components/main/PopularSection.tsx
  src/components/user/my/UserSelectionSection.tsx
  src/components/user/my/UserSelectionTempList.tsx
  src/constants/myPage.constants.ts
  src/constants/selection.constants.ts
  src/hooks/useHandleCardMenu.ts
  src/services/selectionUser.services.ts
Labels: enhancement

#231 Refactor/#230 loading UI
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/common/PageError.tsx
  src/components/common/PageLoading.tsx
  src/components/search/search-contents/SearchLoading.tsx
Labels: refactor

#233 FEAT : 로그인 x 일 때 북마크,문의하기 로직 수정
  src/components/common/Footer.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/hooks/mutations/useBookMarks.ts
Labels: refactor

#236 Feature/#131 winston logging implementation
  package-lock.json
  package.json
  src/app/api/selections/[selectionId]/route.ts
  src/app/api/selections/categories/route.ts
  src/app/api/selections/locations/route.ts
  src/app/api/selections/route.ts
  src/app/api/selections/suggest-hashtags/route.ts
  src/app/api/temporary-selections/[selectionId]/route.ts
  src/app/api/temporary-selections/route.ts
  src/instrumentation.ts.bk
  src/libs/winston.ts
  src/repositories/hashtag.repository.ts
  src/repositories/selection.repository.ts
  src/repositories/spot.repository.ts
  src/services/selection.services.ts
  src/utils/logUtils.ts
Labels: enhancement

#238 Fix: Header Session issue
  src/app/ClientRoot.tsx
  src/components/common/Header.tsx
  src/components/users/ModalSignIn.tsx
Labels: bug

#239 Refactor : 빌드 관련 파일 리펙토링
  .gitignore
  entrypoint.sh
Labels: bug, enhancement

#240 Remove: 셀렉션 추천 사용법 시연 전용 route 삭제
  src/app/api/route.ts
Labels: invalid, refactor

#241 Refactor/#234 review image
  src/components/selection-detail/review/ReviewForm.tsx
  src/components/selection-detail/review/ReviewImageModal.tsx
  src/components/selection-detail/review/ReviewImageSlideButton.tsx
  src/components/selection-detail/review/ReviewImages.tsx
  src/components/selection-detail/review/ReviewModalImage.tsx
Labels: refactor

#242 Feat/#235 사용자 맞춤 셀렉션
  src/app/api/selections/recommendations/route.ts
  src/app/api/users/[userId]/hashtag/route.ts
  src/components/common/card/RowCard.tsx
  src/components/main/InterestingSection.tsx
  src/constants/queryKey.constants.ts
  src/hooks/queries/useFetchRecommendationSelection.ts
  src/http/selectionMain.api.ts
  src/instrumentation.ts
  src/services/selectionMain.services.ts
Labels: enhancement

#247 Feat : 사용자 맞춤 셀렉션 북마크 여부 확인 쿼리문 추가, 전체 보기 제거
  src/components/main/InterestingSection.tsx
  src/services/selectionMain.services.ts
Labels: refactor

#249 Fix: Session 추가로 생성하지 않고 next 자체처리
  src/app/ClientRoot.tsx
  src/components/common/Header.tsx
Labels: bug

#262 FEAT : 문의하기 reCAPTCHA 적용
  src/app/api/feedback/route.ts
  src/components/common/modal/modal-contents/ModalFeedbackForm.tsx
Labels: enhancement

#265 Feat : 스켈레톤 UI 추가 및 맞춤 셀렉션 API 분리
  src/app/api/selections/recommendations/route.ts
  src/components/main/InterestingSection.tsx
  src/services/selectionMain.services.ts
Labels: refactor

#276 FEAT : 맞춤 셀렉션 북마크 연결
  src/hooks/mutations/useBookMarks.ts
  src/hooks/queries/useFetchRecommendationSelection.ts
Labels: enhancement

#278 FEAT : 상세 페이지 해시 태그 검색 x , delete,private 상태 셀렉션 접근 x
  src/app/selection/[selectionId]/page.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
Labels: enhancement

#279 Feat: 셀렉션 생성 관련 API 사용 제한
  src/app/api/selections/[selectionId]/details-for-edit/route.ts
  src/app/api/selections/spots/geolocate/route.ts
  src/app/api/selections/spots/reverse-geolocate/route.ts
  src/app/api/selections/spots/search/route.ts
  src/app/api/selections/suggest-hashtags/route.ts
  src/libs/redis.ts
  src/utils/logUtils.ts
  src/utils/redisUtils.ts
Labels: enhancement, refactor

#280 FEAT : 스팟 이미지 로딩 스피너 추가, 이미지 모달창 왼쪽 버튼 클릭 x 해결
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotImages.tsx
Labels: bug, enhancement

#282 FIX : 좋아요 북마크 userId 받아오는 로직 수정
  src/app/api/selections/[selectionId]/bookmarks/route.ts
  src/app/api/selections/[selectionId]/reviews/[reviewId]/likes/route.ts
  src/app/api/selections/[selectionId]/spots/[spotId]/reviews/[reviewId]/likes/route.ts
  src/components/common/card/ColCard.tsx
  src/components/selection-detail/review/ReviewItem.tsx
  src/components/selection-detail/review/ReviewLikeButton.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
  src/hooks/mutations/useBookMarks.ts
  src/hooks/mutations/useReviewsLikes.ts
  src/http/bookmarks.api.ts
  src/http/review.api.ts
Labels: refactor

#283 FIX : useEffect 의존성배열 변경
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
Labels: bug

#285 Fix/#281 메인, 검색, 마이페이지 버그 수정_
  src/app/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/card/ColCard.tsx
  src/components/common/input/TextInput.tsx
  src/components/search/SearchEngineSection.tsx
  src/components/search/SearchResultSection.tsx
  src/constants/selection.constants.ts
  src/hooks/mutations/useDeleteSelection.ts
  src/hooks/mutations/useUpdateUserSelectionPrivate.ts
  src/hooks/useHandleCardMenu.ts
Labels: bug

#284 FEAT : 셀렉션 생성, 수정 시 쿼리 무효화
  src/hooks/useSubmitSelectionCreateForm.tsx
Labels: bug

#287 Fix : 태그 중복 오류, 맞춤 셀렉션 페치 오류, RowCard 닉네임 안보이는 오류 수정
  src/app/page.tsx
  src/components/main/DisplaySection.tsx
  src/components/main/InterestingSection.tsx
  src/components/main/RecommendationSection.tsx
  src/hooks/mutations/useBookMarks.ts
Labels: bug

#292 FEAT : 북마크 색상 변경, Favicon 적용, 리다이렉션 후 새로고침
  public/imgs/SpotLightLogo.png
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/selection/[selectionId]/page.tsx
  src/components/common/card/ColCard.tsx
  src/components/selection-detail/selection-section-contents/SelectionHeader.tsx
Labels: enhancement, refactor

#293 Fix/various fixes by sjw
  Dockerfile
  entrypoint.sh
  package-lock.json
  package.json
  src/app/api/selections/[selectionId]/route.ts
  src/app/api/selections/spots/search/route.ts
  src/app/api/temporary-selections/[selectionId]/route.ts
  src/app/api/temporary-selections/route.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/ModalController.tsx
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotSearchBar.tsx
  src/components/selection-create/SelectionCreateThumbnailImage.tsx
  src/hooks/useGeocoding.ts
  src/hooks/useReverseGeocoding.ts
  src/hooks/useSpotSearch.ts
  src/libs/winston.ts
  src/models/user.model.ts
  src/services/selection.services.ts
  src/services/selectionCreate.services.ts
  src/services/selectionCreate.validation.ts
  src/services/selectionReview.services.ts
  src/services/spot.services.ts
  src/services/user.services.ts
  sys.sh
Labels: bug, enhancement, refactor

#295 Fix/various fixes by sjw
  src/services/selectionEdit.services.ts
  src/services/spot.services.ts
Labels: bug, enhancement

#296 Remove/#297 계정 관리 삭제, 해시태그 유효성 검사 수정
  src/app/api/selections/popular/route.ts
  src/app/api/selections/search/route.ts
  src/app/api/users/[userId]/hashtag/route.ts
  src/app/page.tsx
  src/app/user/[userId]/account/page.tsx
  src/components/common/Header.tsx
  src/components/user/my/UserNavigation.tsx
  src/hooks/mutations/useBookMarks.ts
  src/hooks/useSearchAutoComplete.ts
  src/services/selectionMain.services.ts
Labels: bug

#297 Fix: 셀렉션 상세 페이지에서 스트리트 뷰 제거
  src/components/google-map/GoogleMap.tsx
Labels: enhancement, refactor

#299 Feat: 이미지 로딩 문제 해결책
  next.config.mjs
Labels: bug

#300 Fix: 임시 구글 이미지 로딩 버그 추적 관련 코드 추가
  next.config.mjs
  src/app/api/selections/[selectionId]/bookmarks/route.ts
  src/app/api/selections/[selectionId]/route.ts
Labels: bug

#301 Fix: remotePatterns 삭제
  next.config.mjs
Labels: bug

#302 FIX : unoptimized 적용
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotImages.tsx
Labels: bug

#303 FIX : unoptimized 추가
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotImagesInput.tsx
Labels: bug

#305 Fix: 스팟 수정 로직 변경
  src/repositories/spot.repository.ts
  src/services/spot.services.ts
Labels: bug

#306 Fix: 해시태그 관련 오류 추적 콘솔 로그 추가
  src/repositories/hashtag.repository.ts
  src/services/spot.services.ts
Labels: bug

#307 FIx : image 태그로 변경
  src/components/common/modal/modal-contents/ModelCreateSelectionSpot/ModalCreateSelectionSpotImagesInput.tsx
  src/components/selection-detail/spot-selection-contents/SpotHeader.tsx
  src/components/selection-detail/spot-selection-contents/SpotImages.tsx
Labels: bug
